targetNamespace: ""
parameters: {}
packages:
  - name: instabox
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: phpapp
        binary: false
        main: ""
        runtime: "php:default"
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
